
language: php
php:
  - 7.0.6

before_install:
  - composer self-update

install:
  - make install

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/clover.xml

after_script:
  - php vendor/bin/coveralls -v

cache:
directories: $HOME/.composer/cache

script:
       
