
language: php
php:
  - 7

before_install:
  - composer self-update

install:
  - make install

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

cache:
directories: $HOME/.composer/cache
